name: "CD"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: "Deploy Cloud Functions to GCP"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Inject NPM token into .npmrc
        working-directory: functions
        run: |
          sed -i.bak "s/\${NPM_TOKEN}/${NPM_TOKEN}/g" .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        working-directory: functions
        run: npm ci

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only functions
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Deploy to Firebase
        working-directory: functions
        run: npx firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # serve???
