name: "CD"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: "Deploy Cloud Functions to GCP"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        working-directory: functions
        run: npm ci

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only functions
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Deploy to Firebase
        working-directory: functions
        run: npx firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
